---
version: "3.4"
services:
  dolt:
    platform: "linux/amd64"
    build:
      context: "../"
      dockerfile: "development/Dockerfile-dolt"
    depends_on:
      - "golden"
    command:
      - "dolt"
      - "--ignore-lock-file"
      - "sql-server"
      - "--config=/dolt-config.yaml"
#      - "--golden=root:mypassword@tcp(golden:3366)/"
    env_file:
      - "dev.env"
      - "creds.env"
    volumes:
      - "dolt_data:/var/lib/nautobot"
      - "./dolt-config.yaml:/dolt-config.yaml"
    ports:
      - "3306:3306"
  golden:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"
      MYSQL_DATABASE: "nautobot"
      MYSQL_TCP_PORT: "3366"
    ports:
      - "3366:3366"
    volumes:
      # Unit tests require the createdb permission to clone the database
      - ./mysql-unittests.sql:/docker-entrypoint-initdb.d/mysql-unittests.sql
      - mysqldata_nautobot:/var/lib/mysql
  redis:
    image: "redis:6-alpine"
    command:
      - "sh"
      - "-c"  # this is to evaluate the $REDIS_PASSWORD from the env
      - "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    env_file:
      - "dev.env"
      - "creds.env"
    ports:
      - "6379:6379"
volumes:
  dolt_data: {}
  mysqldata_nautobot:
