---
x-nautobot-build: &nautobot-build
  build:
    args:
      NAUTOBOT_VER: "${NAUTOBOT_VER}"
      PYTHON_VER: "${PYTHON_VER}"
    context: "../"
    dockerfile: "development/Dockerfile"
x-nautobot-base: &nautobot-base
  image: "nautobot-dolt/nautobot:${NAUTOBOT_VER}-py${PYTHON_VER}"
  env_file:
    - "dev.env"
    - "creds.env"
  tty: true

version: "3.4"
services:
  nautobot:
    deploy:
      replicas: 2
    ports:
      - "8080"
    depends_on:
      - "dolt"
      - "redis"
    <<: *nautobot-build
    <<: *nautobot-base
  worker:
    deploy:
      replicas: 2
    entrypoint: "sh -c 'nautobot-server celery worker -l $$NAUTOBOT_LOG_LEVEL'"
    depends_on:
      - "nautobot"
    healthcheck:
      disable: true
    <<: *nautobot-base
  beat:
    entrypoint: "sh -c 'nautobot-server celery beat -l $$NAUTOBOT_LOG_LEVEL'"
    depends_on:
      - "nautobot"
    healthcheck:
      disable: true
    <<: *nautobot-base

