
FROM ubuntu:xenial

RUN apt update && apt install -y curl

RUN mkdir -p /var/lib/nautobot

# ARG DOLT_RELEASE=latest
# RUN curl -L https://github.com/dolthub/dolt/releases/${DOLT_RELEASE}/download/install.sh | bash

COPY dolt_linux_arm64 /usr/local/bin/dolt

RUN dolt config --global --add user.name nautobot
RUN dolt config --global --add user.email opensource@networktocode.COM

WORKDIR /var/lib/nautobot

# maybe this is mapping the port, double check
EXPOSE 3306

ENV DOLT_ENABLE_DB_REVISIONS=true

RUN dolt init

# rename default branch to "main"
RUN dolt branch -m master main
