---
log_level: "debug"

behavior:
  read_only: false
  autocommit: true

user:
  name: "nautobot"
  password: "notverysecurepwd"

listener:
  host: "0.0.0.0"
  port: 3306
  max_connections: 128
  read_timeout_millis: 28800000
  write_timeout_millis: 28800000

databases:
  - name: "nautobot"
    path: "./nautobot"
  - name: "test_nautobot"
    path: "./test_nautobot"
