# Generated by Django 3.1.12 on 2021-06-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dolt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitAncestor",
            fields=[
                ("commit_hash", models.TextField(primary_key=True, serialize=False)),
                ("parent_hash", models.TextField()),
                ("parent_index", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "commit_ancestors",
                "db_table": "dolt_commit_ancestors",
                "managed": False,
            },
        ),
    ]
