# Generated by Django 3.1.13 on 2021-08-10 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dolt', '0005_pullrequest_pullrequestreview_pullrequestreviewcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pullrequestreview',
            old_name='last_updated',
            new_name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='pullrequestreview',
            name='requested_at',
        ),
        migrations.RemoveField(
            model_name='pullrequestreview',
            name='requester',
        ),
        migrations.AlterField(
            model_name='pullrequestreview',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pullrequestreview',
            name='state',
            field=models.IntegerField(null=True),
        ),
    ]
