# Generated by Django 3.1.13 on 2021-08-09 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dolt', '0005_pullrequest_pullrequestreviewcomments_pullrequestreviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
