# Generated by Django 3.1.13 on 2021-07-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_version_control", "0002_branchmeta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conflicts",
            fields=[
                ("table", models.TextField(primary_key=True, serialize=False)),
                ("num_conflicts", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "conflicts",
                "db_table": "dolt_conflicts",
                "managed": False,
            },
        ),
    ]
